source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'FastttCamera'

platform :ios, '7.0'

def install_pods
  pod "FastttCamera", :path => "../FastttCamera.podspec"
  pod 'Masonry', '0.6.1'
end

target 'FastttCamera', :exclusive => true do
  install_pods
end

target 'FastttCameraTests', :exclusive => true do
  install_pods
  pod 'Specta'
  pod 'Expecta'
  pod 'Expecta+Snapshots'
  pod 'OCMock'
end
