source 'https://github.com/CocoaPods/Specs.git'

project 'FastttCamera'

platform :ios, '7.0'

target 'FastttCamera' do
  pod 'FastttCamera', :path => '../FastttCamera.podspec'
  pod 'Masonry', '0.6.1'

  target 'FastttCameraTests' do
    pod 'Specta'
    pod 'Expecta'
    pod 'Expecta+Snapshots'
    pod 'OCMock'
  end
end
