source 'https://github.com/CocoaPods/Specs.git'

project 'FastttCameraDemo'

platform :ios, '7.0'

def install_pods
  pod "FastttCamera/Filters", :path => "../FastttCamera.podspec"
  pod 'Masonry', '0.6.1'
end

target 'FastttCameraDemo' do
  install_pods

  target 'FastttCameraDemoTests' do
    pod 'Specta'
    pod 'Expecta'
    pod 'Expecta+Snapshots'
    pod 'OCMock'
  end
end
