source 'https://github.com/CocoaPods/Specs.git'

project 'FastttCameraDemo'

platform :ios, '7.0'

target 'FastttCameraDemo' do
  pod 'FastttCamera/Filters', :path => '../FastttCamera.podspec'
  pod 'Masonry', '0.6.1'

  target 'FastttCameraDemoTests' do
    pod 'Specta'
    pod 'Expecta'
    pod 'Expecta+Snapshots'
    pod 'OCMock'
  end
end
